export type { LegacyMapFixtureOptions } from './helpers/testUtils.js';
export {
	asPartial,
	asType,
	buildCleanedBlocksBlock,
	buildEncryptedV1MapPayload,
	buildGenericBlock,
	buildImageBlock,
	buildLegacyMapBuffer,
	buildMapHeader,
	buildPositionBlock,
	createMockAuthApi,
	createMockConfigManager,
	createMockDeviceRegistry,
	createMockIotApi,
	createMockLocalStorage,
	createMockLogger,
	createMockRoborockService,
	LEGACY_BLOCK_TYPE,
	makeLocalClientStub,
	createMockLogger as makeLogger,
	makeMockClientRouter,
} from './helpers/testUtils.js';
