export enum Q10RequestCode {
  clean_time = 6,
  clean_area = 7,
  seek = 11,
  remote = 12,
  map_reset = 13,
  request = 16,
  reset_side_brush = 18,
  reset_main_brush = 20,
  reset_filter = 22,
  rag_life = 23,
  reset_rag_life = 24,
  not_disturb = 25,
  volume = 26,
  beak_clean = 27,
  total_clean_area = 29,
  total_clean_count = 30,
  total_clean_time = 31,
  timer = 32,
  not_disturb_data = 33,
  device_info = 34,
  voice_package = 35,
  voice_language = 36,
  dust_switch = 37,
  custom_mode = 39,
  mop_state = 40,
  unit = 42,
  carpet_clean_prefer = 44,
  auto_boost = 45,
  child_lock = 47,
  dust_setting = 50,
  map_save_switch = 51,
  clean_record = 52,
  recent_clean_record = 53,
  restricted_zone = 54,
  restricted_zone_up = 55,
  virtual_wall = 56,
  virtual_wall_up = 57,
  zoned = 58,
  zoned_up = 59,
  multi_map_switch = 60,
  multimap = 61,
  customer_clean = 62,
  customer_clean_request = 63,
  get_carpet = 64,
  carpet_up = 65,
  self_identifying_carpet = 66,
  sensor_life = 67,
  reset_sensor = 68,
  request_timer = 69,
  remove_zoned = 70,
  remove_zoned_up = 71,
  room_merge = 72,
  room_split = 73,
  reset_room_name = 74,
  request_not_disturb_data = 75,
  carpet_clean_type = 76,
  button_light_switch = 77,
  clean_line = 78,
  timezone = 79,
  area_unit = 80,
  networkinfo = 81,
  clean_order = 82,
  robot_type = 83,
  log_switch = 84,
  floor_material = 85,
  line_laser_obstacle_avoidance = 86,
  clean_progress = 87,
  ground_clean = 88,
  ignore_obstacle = 89,
  fault = 90,
  clean_expand = 91,
  not_disturb_expand = 92,
  timer_type = 93,
  create_map_finished = 94,
  add_clean_area = 95,
  add_clean_state = 96,
  restricted_area = 97,
  restricted_area_up = 98,
  suspected_threshold = 99,
  suspected_threshold_up = 100,
  rpc_request = 101,
  rpc_response = 102,
  cliff_restricted_area_up = 103,
  breakpoint_clean = 104,
  valley_point_charging = 105,
  valley_point_charging_data_up = 106,
  valley_point_charging_data = 107,
  voice_version = 108,
  robot_country_code = 109,
  heart_beat = 110,

  error_code = 120,
  state = 121,
  battery = 122,
  fan_power = 123,
  water_box_mode = 124,
  main_brush_life = 125,
  side_brush_life = 126,
  filter_life = 127,
  additional_props = 128,
  task_complete = 130,
  task_cancel_low_power = 131,
  task_cancel_in_motion = 132,
  charge_status = 133,
  drying_status = 134,
  offline_status = 135,
  clean_times = 136,
  cleaning_reference = 137,
  clean_task_type = 138,
  back_type = 139,
  dock_task_type = 140,
  cleaning_progress = 141,
  fc_state = 142,

  app_start = 201,
  start_back = 202,
  app_charge = 203,
  app_pause = 204,
  app_resume = 205,
  app_stop = 206,
  ceip = 207,

  map_response = 301,
  some_thing_happened_when_socket_closed = 500,
  get_prop = 999, // TODO: Verify
}

// Python B01_Q10_DP name conflicts (kept current TS names):
// 101: rpc_request  → Python: common / jump_scan
// 102: rpc_response → Python: request_dps / cliff_restricted_area
// 121: state        → Python: status
// 124: water_box_mode      → Python: water_level
// 135: offline_status      → Python: offline
// 136: clean_times         → Python: clean_count
// 137: cleaning_reference  → Python: clean_mode
// 142: fc_state            → Python: fleeing_goods
// 201: app_start           → Python: start_clean
// 203: app_charge          → Python: start_dock_task
// 204: app_pause           → Python: pause
// 205: app_resume          → Python: resume
// 206: app_stop            → Python: stop
// 207: ceip                → Python: user_plan

export enum Q10RequestMethod {
  multimap = 61,
  change_vacuum_mode = 123,
  change_mop_mode = 124,
  change_clean_mode = 137,
}
